import { createFileRoute, Link } from "@tanstack/react-router";
import { ExternalLink } from "lucide-react";
import { HistoricalCheckpointLine, MonthlyLine } from "@/components/audience/charts";
import { PageFrame, Panel } from "@/components/audience/page-frame";
import { useAudienceMonitor } from "@/hooks/use-audience-monitor";
import { checkpointRange, dashboardSummary, findArtist, formatDate, formatMonth, formatNumber, formatPercent, formatSigned, historicalPerformance, monthlyConsistency, monthlyPerformance, monthRange, percentile, platformLabel, recordHigh, trajectory } from "@/lib/audience-selectors";
import type { HistoricalPoint } from "@/lib/audience-types";

export const Route = createFileRoute("/_dashboard/artists/$artist")({
  head: ({ params }) => ({ meta: [{ title: `${decodeURIComponent(params.artist)} | Minor AM` }, { name: "description", content: "Live Minor AM artist audience profile and recorded Instagram history." }, { property: "og:title", content: `${decodeURIComponent(params.artist)} | Minor AM` }, { property: "og:description", content: "Live Minor AM artist audience profile and recorded Instagram history." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }),
  component: ArtistProfile,
});

function ArtistProfile() {
  const { artist: slug } = Route.useParams(); const { data } = useAudienceMonitor();
  if (!data) return null;
  const artist = findArtist(data.artists, slug);
  if (!artist) return <PageFrame eyebrow="Artists" title="Artist not found."><Link to="/artists" className="text-sm text-primary">Back to artists</Link></PageFrame>;
  const summary = dashboardSummary(data);
  const platforms = [{ label: "Instagram", value: artist.instagram.audience, date: artist.instagram.observedAt, source: artist.instagram.source }, { label: "SoundCloud", value: artist.soundcloud.audience, date: artist.soundcloud.observedAt, source: artist.soundcloud.source }, { label: "Resident Advisor", value: artist.residentAdvisor.audience, date: artist.residentAdvisor.observedAt, source: artist.residentAdvisor.source }];
  const rankingSets = [["Current IG", summary.currentRank], ["Growth %", summary.growthRank], ["Follower gain", summary.gainRank], ["SoundCloud", [...data.artists].filter((entry) => entry.soundcloud.audience !== null).sort((a, b) => (b.soundcloud.audience ?? -1) - (a.soundcloud.audience ?? -1))], ["Resident Advisor", [...data.artists].filter((entry) => entry.residentAdvisor.audience !== null).sort((a, b) => (b.residentAdvisor.audience ?? -1) - (a.residentAdvisor.audience ?? -1))]] as const;
  const monthly = artist.monthlyHistory.map((point, index) => { const previousPoint = artist.monthlyHistory[index - 1]; const previous = previousPoint?.followers ?? null; const change = point.followers !== null && previous !== null && point.month !== previousPoint?.month ? point.followers - previous : null; return { ...point, change, pct: change !== null && previous ? (change / previous) * 100 : null }; });
  const performance = monthlyPerformance(artist); const instagramHistorical = historicalPerformance(artist.historical.instagram); const soundcloudHistorical = historicalPerformance(artist.historical.soundcloud);
  const currentPercentile = percentile(artist.instagram.audience, data.artists.map((entry) => entry.instagram.audience)); const growthPercentile = percentile(artist.instagram.growthPercent, data.artists.map((entry) => entry.instagram.growthPercent));
  const description = [artist.location, artist.role].filter((item): item is string => typeof item === "string").join(" · ");
  const profileDetails = [["Location", artist.location], ["Role", artist.role], ["Instagram handle", artist.instagramHandle ? `@${artist.instagramHandle.replace(/^@/, "")}` : null], ["Instagram baseline", artist.instagram.baseline === null ? "—" : formatNumber(artist.instagram.baseline)], ["Baseline observed", formatDate(artist.instagram.baselineAt)], ["Latest sheet observation", formatDate(data.latestSourceObservation, true)], ["Dashboard refreshed", formatDate(data.refreshedAt, true)]];
  return <PageFrame eyebrow="Artist profile" title={artist.name} description={description}>
    <div className="grid border-y border-border sm:grid-cols-3">{platforms.map((platform) => <div key={platform.label} className="border-b border-r border-border p-5 sm:border-b-0"><p className="text-[10px] uppercase tracking-[.12em] text-muted-foreground">{platform.label}</p><p className="mt-3 text-2xl font-semibold">{platform.value === null ? "—" : formatNumber(platform.value)}</p><p className="mt-1 text-xs text-muted-foreground">{platform.date && platform.source ? `Source: ${platform.source} · ${formatDate(platform.date)}` : "Awaiting first live observation"}</p></div>)}</div>
    <section className="mt-10 grid gap-10 xl:grid-cols-[1.1fr_.9fr]"><Panel title="Current Instagram movement"><div className="grid grid-cols-2 gap-6"><Metric label="Follower change" value={formatSigned(artist.instagram.change)}/><Metric label="Growth" value={formatPercent(artist.instagram.growthPercent)}/></div><p className="mt-5 text-xs text-muted-foreground">{artist.instagram.change === null ? "Insufficient history for current movement" : checkpointRange(artist.instagram.baselineAt, artist.instagram.observedAt)}</p></Panel><Panel title="Roster rankings"><div className="space-y-2">{rankingSets.map(([label, roster]) => <div className="flex justify-between border-b border-border py-2 text-sm" key={label}><span>{label}</span><b>{roster.findIndex((entry) => entry.name === artist.name) + 1 || "—"}</b></div>)}</div></Panel></section>
    <section className="mt-10 grid gap-10 xl:grid-cols-3"><Panel title="Roster context"><dl className="space-y-3 text-sm"><div className="flex justify-between"><dt>Instagram audience</dt><dd>{currentPercentile === null ? "—" : `Top ${Math.max(1, Math.round(100 - currentPercentile + 1))}%`}</dd></div><div className="flex justify-between"><dt>Current growth</dt><dd>{growthPercentile === null ? "—" : `Top ${Math.max(1, Math.round(100 - growthPercentile + 1))}%`}</dd></div></dl></Panel><Panel title="Monthly signal"><p className="font-serif text-3xl">{trajectory(artist.monthlyHistory)}</p><p className="mt-3 text-sm text-muted-foreground">{monthlyConsistency(artist)}</p></Panel><Panel title="Recorded range"><p className="text-2xl font-semibold">{performance ? formatSigned(performance.change) : "—"}</p><p className="mt-2 text-sm text-muted-foreground">{performance ? `${monthRange(performance.start.month, performance.end.month)} · ${formatPercent(performance.growthPercent)}` : "Insufficient valid monthly history"}</p>{recordHigh(artist) && <p className="mt-3 text-xs font-medium uppercase tracking-[.12em] text-primary">New recorded high</p>}</Panel></section>
    <section className="mt-10"><Panel title="Recorded monthly Instagram"><MonthlyLine artists={[artist]} /><p className="mt-3 text-xs text-muted-foreground">Each month uses the latest trusted checkpoint, preferring Minor AM monitoring where available.</p></Panel></section>
    <section className="mt-10 grid gap-10 xl:grid-cols-[1.1fr_.9fr]"><Panel title="Monthly development"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-border text-xs text-muted-foreground"><tr><th scope="col" className="pb-2">Month</th><th scope="col">Followers</th><th scope="col">Change</th><th scope="col">Growth</th></tr></thead><tbody>{monthly.map((point) => <tr className="border-b border-border" key={point.month}><td className="py-3">{formatMonth(point.month)}</td><td className="tabular-nums">{formatNumber(point.followers)}</td><td className="tabular-nums">{formatSigned(point.change)}</td><td className="tabular-nums">{formatPercent(point.pct)}</td></tr>)}</tbody></table></div></Panel><Panel title="Profile details"><dl className="space-y-3 text-sm">{profileDetails.map(([label, value]) => <div className="flex items-start justify-between gap-4 border-b border-border pb-3" key={label}><dt className="text-muted-foreground">{label}</dt><dd className="max-w-[58%] text-right">{value ?? "—"}</dd></div>)}</dl><div className="mt-8 space-y-3">{Object.entries(artist.urls).map(([platform, url]) => <div key={platform} className="flex items-center gap-2 text-sm">{url ? <a className="flex items-center gap-2 text-primary hover:underline" href={url} target="_blank" rel="noreferrer">{platformLabel(platform as "instagram" | "soundcloud" | "residentAdvisor")}<ExternalLink className="size-3" aria-hidden="true"/></a> : <span className="text-muted-foreground">{platformLabel(platform as "instagram" | "soundcloud" | "residentAdvisor")} · Not linked yet</span>}</div>)}</div></Panel></section>
    {(artist.historical.instagram.length > 0 || artist.historical.soundcloud.length > 0) && <section className="mt-10"><div className="mb-6"><p className="text-[10px] uppercase tracking-[.12em] text-muted-foreground">Checkpoint history</p><h2 className="mt-2 font-serif text-3xl">Recorded source history</h2><p className="mt-2 text-sm text-muted-foreground">These checkpoints inform current values until a newer Minor AM monitoring observation is available.</p></div><div className="grid gap-10 xl:grid-cols-2">{artist.historical.instagram.length > 0 && <HistoricalCheckpointPanel platform="Instagram" history={artist.historical.instagram} performance={instagramHistorical}/>} {artist.historical.soundcloud.length > 0 && <HistoricalCheckpointPanel platform="SoundCloud" history={artist.historical.soundcloud} performance={soundcloudHistorical}/>}</div></section>}
  </PageFrame>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>; }
function HistoricalCheckpointPanel({ platform, history, performance }: { platform: "Instagram" | "SoundCloud"; history: HistoricalPoint[]; performance: ReturnType<typeof historicalPerformance> }) { const source = history[0]?.source ?? "Viberate"; return <Panel title={`${platform} historical checkpoints`}><p className="text-sm text-muted-foreground">{source} historical checkpoints · {checkpointRange(history[0]?.date, history.at(-1)?.date)}</p><div className="mt-5 grid grid-cols-2 gap-x-6 gap-y-5 text-sm sm:grid-cols-4"><HistoricalStat label="First checkpoint" value={formatNumber(history[0]?.followers)}/><HistoricalStat label="Latest checkpoint" value={formatNumber(history.at(-1)?.followers)}/><HistoricalStat label="Follower change" value={formatSigned(performance?.change)}/><HistoricalStat label="Growth" value={formatPercent(performance?.growthPercent)}/></div><div className="mt-7"><HistoricalCheckpointLine history={history} platform={platform}/></div></Panel>; }
function HistoricalStat({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-semibold">{value}</p></div>; }