import { useId } from "react";
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, ScatterChart, Scatter, CartesianGrid, BarChart, Bar, Cell, ReferenceLine } from "recharts";
import type { ArtistRecord } from "@/lib/audience-types";
import { formatNumber, formatPercent, formatSigned } from "@/lib/audience-selectors";

const positive = "var(--chart-2)", negative = "var(--destructive)", primary = "var(--primary)";
export function Sparkline({ artist }: { artist: ArtistRecord }) { const id = useId(); const data=artist.monthlyHistory.filter(p=>p.followers!==null); if(data.length<2) return <span className="text-xs text-muted-foreground">—</span>; return <div className="h-8 w-20"><ResponsiveContainer><LineChart data={data}><defs><linearGradient id={id}/></defs><Line type="monotone" dataKey="followers" stroke={primary} strokeWidth={1.5} dot={false}/></LineChart></ResponsiveContainer></div> }
export function MonthlyLine({ artists }: { artists: ArtistRecord[] }) { const months=[...new Set(artists.flatMap(a=>a.monthlyHistory.map(p=>p.month)))]; const data=months.map(month=>Object.fromEntries([['month',month],...artists.map(a=>[a.name,a.monthlyHistory.find(p=>p.month===month)?.followers ?? null]) ])); return <div className="h-80"><ResponsiveContainer><LineChart data={data}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="month" tick={{fill:"var(--muted-foreground)",fontSize:11}}/><YAxis tickFormatter={(v)=>formatNumber(v)} tick={{fill:"var(--muted-foreground)",fontSize:11}}/><Tooltip contentStyle={{background:"var(--popover)",borderColor:"var(--border)"}}/>{artists.map((artist,index)=><Line key={artist.name} dataKey={artist.name} type="monotone" connectNulls={false} stroke={`var(--chart-${(index%5)+1})`} strokeWidth={2} dot={{r:3}}/>)}</LineChart></ResponsiveContainer></div> }
export function MoversChart({ artists, mode }: { artists: ArtistRecord[]; mode: "change"|"growth" }) { const valueFor = (artist: ArtistRecord) => mode === "change" ? artist.instagram.change : artist.instagram.growthPercent; const data=[...artists].filter(a=>valueFor(a)!==null).sort((a,b)=>(valueFor(b)??0)-(valueFor(a)??0)).slice(0,8).map(a=>({name:a.name,value:valueFor(a)??0})); return <div className="h-80"><ResponsiveContainer><BarChart data={data} layout="vertical" margin={{left:20}}><XAxis type="number" tickFormatter={(v)=>mode==="growth"?`${v}%`:formatNumber(v)} tick={{fill:"var(--muted-foreground)",fontSize:11}}/><YAxis type="category" dataKey="name" width={112} tick={{fill:"var(--foreground)",fontSize:12}}/><Tooltip formatter={(v)=>mode==="growth"?formatPercent(Number(v)):formatSigned(Number(v))} contentStyle={{background:"var(--popover)",borderColor:"var(--border)"}}/><ReferenceLine x={0} stroke="var(--border)"/><Bar dataKey="value">{data.map((item)=><Cell key={item.name} fill={item.value>=0?positive:negative}/>)}</Bar></BarChart></ResponsiveContainer></div> }
export function GrowthScatter({ artists }: { artists: ArtistRecord[] }) { const data=artists.filter(a=>a.instagram.audience!==null&&a.instagram.growthPercent!==null).map(a=>({name:a.name,x:Math.log10(a.instagram.audience ?? 1),followers:a.instagram.audience,growth:a.instagram.growthPercent,change:a.instagram.change})); return <div className="h-80"><ResponsiveContainer><ScatterChart margin={{top:10,right:20,bottom:20,left:0}}><CartesianGrid stroke="var(--border)"/><XAxis dataKey="x" name="Current IG" tickFormatter={(v)=>formatNumber(Math.round(10**v))} tick={{fill:"var(--muted-foreground)",fontSize:11}}/><YAxis dataKey="growth" name="Growth" tickFormatter={(v)=>`${v}%`} tick={{fill:"var(--muted-foreground)",fontSize:11}}/><Tooltip cursor={{strokeDasharray:"3 3"}} content={({active,payload})=>active&&payload?.[0]?<div className="border border-border bg-popover px-3 py-2 text-xs text-popover-foreground"><strong>{payload[0].payload.name}</strong><br/>Current IG {formatNumber(payload[0].payload.followers)}<br/>Gain {formatSigned(payload[0].payload.change)}<br/>Growth {formatPercent(payload[0].payload.growth)}</div>:null}/><Scatter data={data} fill={primary}/></ScatterChart></ResponsiveContainer></div> }
