import { useId } from "react";
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, ScatterChart, Scatter, CartesianGrid, BarChart, Bar, Cell, ReferenceLine } from "recharts";
import type { ArtistRecord, HistoricalPoint } from "@/lib/audience-types";
import { formatDate, formatMonth, formatNumber, formatPercent, formatSigned } from "@/lib/audience-selectors";

const positive = "var(--chart-2)", negative = "var(--destructive)", primary = "var(--primary)";
// Recharts renders an SVG with no inherent text alternative — each chart gets
// a one-line sr-only summary of what it shows, and the visual chart itself is
// hidden from assistive tech so a screen reader doesn't instead read through
// meaningless SVG/tooltip internals.
function ChartFigure({ summary, height, children }: { summary: string; height: string; children: React.ReactNode }) {
  return <div className={height}><span className="sr-only">{summary}</span><div aria-hidden="true" className="h-full">{children}</div></div>;
}
export function Sparkline({ artist }: { artist: ArtistRecord }) { const id = useId(); const data=artist.monthlyHistory.filter(p=>p.followers!==null); if(data.length<2) return <span className="text-xs text-muted-foreground">—</span>; const summary=`${artist.name} Instagram trend: ${formatNumber(data[0]?.followers)} to ${formatNumber(data.at(-1)?.followers)} across ${data.length} recorded months.`; return <ChartFigure summary={summary} height="h-8 w-20"><ResponsiveContainer><LineChart data={data}><defs><linearGradient id={id}/></defs><Line type="monotone" dataKey="followers" stroke={primary} strokeWidth={1.5} dot={false}/></LineChart></ResponsiveContainer></ChartFigure> }
export function MonthlyLine({ artists }: { artists: ArtistRecord[] }) { const months=[...new Set(artists.flatMap(a=>a.monthlyHistory.map(p=>p.month)))]; const data=months.map(month=>Object.fromEntries([['month',month],...artists.map(a=>[a.name,a.monthlyHistory.find(p=>p.month===month)?.followers ?? null]) ])); const summary=`Monthly Instagram followers for ${artists.map(a=>a.name).join(", ")} across ${months.length} recorded months.`; return <ChartFigure summary={summary} height="h-80"><ResponsiveContainer><LineChart data={data}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="month" tickFormatter={(v)=>formatMonth(v)} tick={{fill:"var(--muted-foreground)",fontSize:11}}/><YAxis tickFormatter={(v)=>formatNumber(v)} tick={{fill:"var(--muted-foreground)",fontSize:11}}/><Tooltip labelFormatter={(v)=>formatMonth(String(v))} contentStyle={{background:"var(--popover)",borderColor:"var(--border)"}}/>{artists.map((artist,index)=><Line key={artist.name} dataKey={artist.name} type="monotone" connectNulls={false} stroke={`var(--chart-${(index%5)+1})`} strokeWidth={2} dot={{r:3}}/>)}</LineChart></ResponsiveContainer></ChartFigure> }
export function HistoricalCheckpointLine({ history, platform }: { history: HistoricalPoint[]; platform: "Instagram" | "SoundCloud" }) { if (history.length < 2) return <p className="text-sm text-muted-foreground">Insufficient historical checkpoints.</p>; const summary=`${platform} followers from ${formatDate(history[0]?.date)} (${formatNumber(history[0]?.followers)}) to ${formatDate(history.at(-1)?.date)} (${formatNumber(history.at(-1)?.followers)}).`; return <ChartFigure summary={summary} height="h-72"><ResponsiveContainer><LineChart data={history} margin={{ top: 10, right: 12, left: 0, bottom: 0 }}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="date" tickFormatter={(value) => formatDate(value)} tick={{ fill: "var(--muted-foreground)", fontSize: 11 }} minTickGap={28}/><YAxis tickFormatter={(value) => formatNumber(value)} tick={{ fill: "var(--muted-foreground)", fontSize: 11 }}/><Tooltip contentStyle={{ background: "var(--popover)", borderColor: "var(--border)" }} labelFormatter={(value) => formatDate(String(value))} formatter={(value) => [formatNumber(typeof value === "number" ? value : null), `${platform} followers`]}/><Line type="monotone" dataKey="followers" stroke={primary} strokeWidth={2} dot={{ r: 3, fill: primary }} activeDot={{ r: 5 }}/></LineChart></ResponsiveContainer></ChartFigure> }
export function RosterMonthlyTrend({ data }: { data: { month: string; audience: number | null; coverage: number }[] }) { const valid=data.filter(p=>p.audience!==null); const summary=valid.length?`Roster-wide monthly Instagram followers across ${data.length} recorded months, from ${formatNumber(valid[0]?.audience)} to ${formatNumber(valid.at(-1)?.audience)}.`:"No recorded monthly Instagram data yet."; return <ChartFigure summary={summary} height="h-72"><ResponsiveContainer><LineChart data={data} margin={{top:10,right:12,left:0,bottom:0}}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="month" tickFormatter={(v)=>formatMonth(v)} tick={{fill:"var(--muted-foreground)",fontSize:11}}/><YAxis tickFormatter={(value)=>formatNumber(value)} tick={{fill:"var(--muted-foreground)",fontSize:11}}/><Tooltip contentStyle={{background:"var(--popover)",borderColor:"var(--border)"}} formatter={(value)=>formatNumber(typeof value === "number" ? value : null)} labelFormatter={(label)=>`${formatMonth(String(label))} · recorded Instagram followers`}/><Line type="monotone" dataKey="audience" connectNulls={false} stroke={primary} strokeWidth={2} dot={{r:3,fill:primary}} activeDot={{r:5}}/></LineChart></ResponsiveContainer></ChartFigure> }
export function MoversChart({ artists, mode }: { artists: ArtistRecord[]; mode: "change"|"growth" }) { const valueFor = (artist: ArtistRecord) => mode === "change" ? artist.instagram.change : artist.instagram.growthPercent; const data=[...artists].filter(a=>valueFor(a)!==null).sort((a,b)=>(valueFor(b)??0)-(valueFor(a)??0)).slice(0,8).map(a=>({name:a.name,value:valueFor(a)??0})); const format=mode==="growth"?formatPercent:formatSigned; const summary=data.length?`Top artists by ${mode==="growth"?"Instagram growth percentage":"Instagram follower gain"}: ${data.map(d=>`${d.name} ${format(d.value)}`).join(", ")}.`:"No comparable current-period movement yet."; return <ChartFigure summary={summary} height="h-80"><ResponsiveContainer><BarChart data={data} layout="vertical" margin={{left:20}}><XAxis type="number" tickFormatter={(v)=>mode==="growth"?`${v}%`:formatNumber(v)} tick={{fill:"var(--muted-foreground)",fontSize:11}}/><YAxis type="category" dataKey="name" width={112} tick={{fill:"var(--foreground)",fontSize:12}}/><Tooltip formatter={(v)=>mode==="growth"?formatPercent(Number(v)):formatSigned(Number(v))} contentStyle={{background:"var(--popover)",borderColor:"var(--border)"}}/><ReferenceLine x={0} stroke="var(--border)"/><Bar dataKey="value">{data.map((item)=><Cell key={item.name} fill={item.value>=0?positive:negative}/>)}</Bar></BarChart></ResponsiveContainer></ChartFigure> }
export function GrowthScatter({ artists }: { artists: ArtistRecord[] }) { const data=artists.filter(a=>a.instagram.audience!==null&&a.instagram.growthPercent!==null).map(a=>({name:a.name,x:Math.log10(a.instagram.audience ?? 1),followers:a.instagram.audience,growth:a.instagram.growthPercent,change:a.instagram.change})); const summary=`Current Instagram audience versus growth percentage for ${data.length} artists with comparable data.`; return <ChartFigure summary={summary} height="h-80"><ResponsiveContainer><ScatterChart margin={{top:10,right:20,bottom:20,left:0}}><CartesianGrid stroke="var(--border)"/><XAxis dataKey="x" name="Current IG" tickFormatter={(v)=>formatNumber(Math.round(10**v))} tick={{fill:"var(--muted-foreground)",fontSize:11}}/><YAxis dataKey="growth" name="Growth" tickFormatter={(v)=>`${v}%`} tick={{fill:"var(--muted-foreground)",fontSize:11}}/><Tooltip cursor={{strokeDasharray:"3 3"}} content={({active,payload})=>active&&payload?.[0]?<div className="border border-border bg-popover px-3 py-2 text-xs text-popover-foreground"><strong>{payload[0].payload.name}</strong><br/>Current IG {formatNumber(payload[0].payload.followers)}<br/>Gain {formatSigned(payload[0].payload.change)}<br/>Growth {formatPercent(payload[0].payload.growth)}</div>:null}/><Scatter data={data} fill={primary}/></ScatterChart></ResponsiveContainer></ChartFigure> }
