import { Link, useRouterState } from "@tanstack/react-router";
import { BarChart3, BookOpen, ChartNoAxesCombined, GitCompareArrows, History, Lightbulb, Menu, RefreshCw, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { LogoMark } from "@/components/audience/logo-mark";
import { formatDate } from "@/lib/audience-selectors";
import type { AudienceMonitorData } from "@/lib/audience-types";

const navigation = [{to:"/",label:"Pulse",icon:ChartNoAxesCombined},{to:"/artists",label:"Artists",icon:Users},{to:"/compare",label:"Compare",icon:GitCompareArrows},{to:"/rankings",label:"Rankings",icon:BarChart3},{to:"/monthly-history",label:"Monthly History",icon:History},{to:"/insights",label:"Insights",icon:Lightbulb},{to:"/methodology",label:"Methodology",icon:BookOpen}] as const;
export function DashboardShell({ data, isRefreshing, onRefresh, children }: {data:AudienceMonitorData;isRefreshing:boolean;onRefresh:()=>void;children:React.ReactNode}) { const path=useRouterState({select:s=>s.location.pathname}); return <div className="min-h-screen bg-background text-foreground"><aside className="fixed inset-y-0 left-0 z-20 hidden w-60 border-r border-border bg-card px-4 py-6 lg:block"><div className="mb-10 flex items-center gap-3 px-2"><LogoMark className="size-11"/><div><p className="font-serif text-2xl leading-none">Minor AM</p><p className="mt-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-muted-foreground">Audience intelligence</p></div></div><nav className="space-y-1">{navigation.map(({to,label,icon:Icon})=><Link key={to} to={to} className={`flex items-center gap-3 px-3 py-2.5 text-sm transition-colors ${path===to?"bg-secondary font-semibold text-foreground":"text-muted-foreground hover:bg-muted hover:text-foreground"}`}><Icon className="size-4"/>{label}</Link>)}</nav><p className="absolute bottom-6 px-2 text-xs leading-5 text-muted-foreground">Live audience monitoring<br/>for Minor AM artists</p></aside><header className="sticky top-0 z-10 border-b border-border bg-background/95 backdrop-blur lg:ml-60"><div className="flex min-h-16 items-center justify-between gap-4 px-5 sm:px-8"><div className="flex items-center gap-2 lg:hidden"><LogoMark className="size-8"/><p className="font-serif text-xl">Minor AM</p></div><div className="hidden text-xs text-muted-foreground sm:block"><span className="font-medium text-foreground">Data through {formatDate(data.latestSourceObservation)}</span><span className="mx-2 text-border">/</span>Refreshed {formatDate(data.refreshedAt, true)}</div><Button variant="outline" size="icon" onClick={onRefresh} disabled={isRefreshing} aria-label="Refresh live data" title="Refresh live data"><RefreshCw className={isRefreshing?"animate-spin":""}/></Button></div><nav className="flex overflow-x-auto border-t border-border px-3 lg:hidden">{navigation.map(({to,label})=><Link key={to} to={to} className={`shrink-0 px-3 py-3 text-xs ${path===to?"border-b-2 border-primary font-semibold text-foreground":"text-muted-foreground"}`}>{label}</Link>)}</nav></header><main className="lg:ml-60">{children}</main></div> }
